version: '3.8'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=todo-db
    ports:
      - "3333:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  app:
    depends_on:
      - mysql
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=todo-db
      - DB_PORT=3333
    stdin_open: true
    tty: true
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge